from __future__ import annotations

import html
import json
import pathlib
import re
import uuid
from typing import Any

from backend.runner.job_runner import STORAGE


def slugify(value: str | None, fallback: str = "upcurved_export", max_len: int = 70) -> str:
    text = str(value or "").strip().lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    if not text:
        text = fallback
    return text[:max_len].strip("_") or fallback


def make_download_filename(kind: str, title: str | None = None) -> str:
    safe_kind = slugify(kind, fallback="export", max_len=24)
    safe_title = slugify(title, fallback="lesson", max_len=60)
    return f"upcurved_{safe_kind}_{safe_title}.html"


def safe_job_id(job_id: str | None = None) -> str:
    raw = str(job_id or "").strip()
    safe = re.sub(r"[^a-zA-Z0-9_-]", "_", raw)[:64]
    return safe or uuid.uuid4().hex[:10]


def save_html_file(job_id: str | None, filename: str, html_text: str) -> pathlib.Path:
    jid = safe_job_id(job_id)
    safe_name = pathlib.Path(filename).name
    if not safe_name.lower().endswith(".html"):
        safe_name += ".html"
    out_dir = STORAGE / "jobs" / jid
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / safe_name
    path.write_text(html_text, encoding="utf-8")
    return path


def _safe_json_for_script(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False).replace("</", "<\\/")


def build_quiz_html(quiz: dict[str, Any], *, source_title: str | None = None) -> str:
    title = str(quiz.get("title") or source_title or "UpcurvEd Quiz").strip()[:120]
    description = str(quiz.get("description") or "Interactive quiz generated by UpcurvEd.").strip()[:280]
    questions_in = quiz.get("questions") if isinstance(quiz.get("questions"), list) else []
    questions: list[dict[str, Any]] = []
    for q in questions_in[:50]:
        if not isinstance(q, dict):
            continue
        prompt = str(q.get("prompt") or "Question").strip()
        options = q.get("options") if isinstance(q.get("options"), list) else []
        opts = [str(o).strip() for o in options if str(o).strip()][:6]
        try:
            correct = int(q.get("correctIndex", 0))
        except Exception:
            correct = 0
        if len(opts) < 2:
            continue
        if correct < 0 or correct >= len(opts):
            correct = 0
        questions.append({"prompt": prompt, "options": opts, "correctIndex": correct})

    data = {"title": title, "description": description, "questions": questions}
    data_json = _safe_json_for_script(data)
    page_title = html.escape(title)
    page_description = html.escape(description)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{page_title}</title>
  <style>
    :root {{ color-scheme: light; --bg:#f8fafc; --card:#ffffff; --ink:#0f172a; --muted:#64748b; --accent:#2563eb; --good:#16a34a; --bad:#dc2626; --line:#e2e8f0; }}
    * {{ box-sizing: border-box; }}
    body {{ margin:0; font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: radial-gradient(circle at top, #dbeafe, var(--bg) 45%); color:var(--ink); }}
    .wrap {{ max-width: 900px; margin: 0 auto; padding: 32px 18px 48px; }}
    .hero {{ background: linear-gradient(135deg, #1d4ed8, #7c3aed); color:white; border-radius:24px; padding:28px; box-shadow:0 18px 45px rgba(30,64,175,.25); }}
    h1 {{ margin:0 0 8px; font-size: clamp(28px, 5vw, 46px); line-height:1.05; }}
    .hero p {{ margin:0; opacity:.9; font-size:17px; }}
    .card {{ margin-top:22px; background:var(--card); border:1px solid var(--line); border-radius:20px; padding:22px; box-shadow:0 12px 30px rgba(15,23,42,.08); }}
    .meta {{ display:flex; justify-content:space-between; gap:12px; color:var(--muted); font-size:14px; margin-bottom:14px; }}
    .prompt {{ font-size:20px; font-weight:700; margin:0 0 18px; }}
    .options {{ display:grid; gap:10px; }}
    button {{ font:inherit; }}
    .option {{ width:100%; text-align:left; border:1px solid var(--line); border-radius:14px; background:#fff; padding:14px 16px; cursor:pointer; transition:.15s ease; }}
    .option:hover {{ border-color:var(--accent); transform:translateY(-1px); }}
    .option.selected {{ border-color:var(--accent); box-shadow:0 0 0 3px rgba(37,99,235,.16); }}
    .option.correct {{ border-color:var(--good); background:#ecfdf5; }}
    .option.incorrect {{ border-color:var(--bad); background:#fef2f2; }}
    .actions {{ display:flex; flex-wrap:wrap; gap:10px; margin-top:18px; }}
    .primary, .secondary {{ border:0; border-radius:999px; padding:11px 16px; cursor:pointer; font-weight:700; }}
    .primary {{ background:var(--accent); color:white; }}
    .secondary {{ background:#e2e8f0; color:#0f172a; }}
    .feedback {{ margin-top:14px; font-weight:700; }}
    .score {{ font-size:32px; font-weight:800; margin:8px 0; }}
    details {{ border:1px solid var(--line); border-radius:16px; background:#fff; padding:14px 16px; }}
    summary {{ cursor:pointer; font-weight:800; }}
    li {{ margin:8px 0; }}
    .footer {{ margin-top:22px; text-align:center; color:var(--muted); font-size:13px; }}
  </style>
</head>
<body>
  <main class="wrap">
    <section class="hero">
      <h1>{page_title}</h1>
      <p>{page_description}</p>
    </section>
    <section class="card" id="quiz-card"></section>
    <div class="footer">Generated with UpcurvEd</div>
  </main>
  <script>
    const quiz = {data_json};
    const card = document.getElementById('quiz-card');
    let index = 0;
    let selected = null;
    let revealed = false;
    let answers = [];

    function letter(i) {{ return String.fromCharCode(65 + i); }}
    function score() {{
      return quiz.questions.reduce((n, q, i) => n + (answers[i] === q.correctIndex ? 1 : 0), 0);
    }}
    function finish() {{
      const s = score();
      card.innerHTML = `
        <div class="meta"><span>Results</span><span>${{quiz.questions.length}} questions</span></div>
        <h2 class="score">${{s}} / ${{quiz.questions.length}}</h2>
        <p>${{s === quiz.questions.length ? 'Perfect score!' : s >= Math.ceil(quiz.questions.length * 0.8) ? 'Great job!' : 'Keep practicing — you can retake it.'}}</p>
        <div class="actions"><button class="primary" id="restart">Retake quiz</button></div>
      `;
      document.getElementById('restart').addEventListener('click', () => {{ index = 0; selected = null; revealed = false; answers = []; render(); }});
    }}
    function render() {{
      if (!quiz.questions.length) {{ card.innerHTML = '<p>No questions were generated.</p>'; return; }}
      if (index >= quiz.questions.length) return finish();
      const q = quiz.questions[index];
      card.innerHTML = `
        <div class="meta"><span>Question ${{index + 1}} of ${{quiz.questions.length}}</span><span>Score: ${{score()}}</span></div>
        <p class="prompt">${{q.prompt}}</p>
        <div class="options"></div>
        <div class="feedback" id="feedback"></div>
        <div class="actions"><button class="primary" id="submit">Submit</button><button class="secondary" id="reset">Restart</button></div>
      `;
      const opts = card.querySelector('.options');
      q.options.forEach((opt, i) => {{
        const b = document.createElement('button');
        b.className = 'option';
        b.textContent = `${{letter(i)}}. ${{opt}}`;
        b.addEventListener('click', () => {{ if (revealed) return; selected = i; renderOptionStates(); }});
        opts.appendChild(b);
      }});
      document.getElementById('submit').addEventListener('click', () => {{
        if (selected == null) {{ document.getElementById('feedback').textContent = 'Choose an answer first.'; return; }}
        if (!revealed) {{ revealed = true; renderOptionStates(); return; }}
        answers[index] = selected; index += 1; selected = null; revealed = false; render();
      }});
      document.getElementById('reset').addEventListener('click', () => {{ index = 0; selected = null; revealed = false; answers = []; render(); }});
      renderOptionStates();
    }}
    function renderOptionStates() {{
      const q = quiz.questions[index];
      const buttons = Array.from(card.querySelectorAll('.option'));
      buttons.forEach((b, i) => {{
        b.className = 'option' + (selected === i ? ' selected' : '') + (revealed && i === q.correctIndex ? ' correct' : '') + (revealed && selected === i && i !== q.correctIndex ? ' incorrect' : '');
      }});
      const fb = document.getElementById('feedback');
      const submit = document.getElementById('submit');
      if (revealed) {{
        fb.textContent = selected === q.correctIndex ? 'Correct!' : `Not quite. Correct answer: ${{letter(q.correctIndex)}}.`;
        submit.textContent = index + 1 === quiz.questions.length ? 'Finish' : 'Next';
      }} else {{
        fb.textContent = '';
        submit.textContent = 'Submit';
      }}
    }}
    render();
  </script>
</body>
</html>"""
